nginx:
  image: nginx-ldap
  container_name: nginx
  ports:
    - 7777:443
  links:
    - registry:registry
  volumes:
    - /home/nigo9731/auth/:/etc/nginx/conf.d
    - /home/nigo9731/auth/registry.conf:/etc/nginx/nginx.conf

registry:
  image: registry:2
  container_name: registry
  environment:
   REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
  volumes:
    - /mnt:/var/lib/registry
